import type { RawMonthlyInput } from "./types";

/** Source: ishaan_excel.xlsx — Raw Data Input blue cells (Jan–Dec 2026) */
export const SEED_RAW_INPUTS: RawMonthlyInput[] = [
  {
    month: "Jan-26",
    activeSubscriptions: 260,
    monthlySubscriptionCost: 5000,
    newSubscriptionsStarted: 16,
    subscriptionsDowngradedMrrLost: 6400,
    subscriptionsCancelled: 5,
    totalOperatingExpenses: 1728000,
    cashAndBankBalance: 20539200,
    totalActiveCustomers: 260,
    newCustomersAcquired: 16,
    customersChurned: 5,
    salesMarketingSpend: 448000,
    leadsGenerated: 176,
    leadsQualified: 109,
    demosCompleted: 59,
    dealsClosedWon: 16,
    npsScore: 52,
    headcount: 36,
    employeesExited: 1,
    openRoles: 5,
    grossMarginAssumption: 0.8,
  },
  {
    month: "Feb-26",
    activeSubscriptions: 266,
    monthlySubscriptionCost: 5000,
    newSubscriptionsStarted: 16,
    subscriptionsDowngradedMrrLost: 6784,
    subscriptionsCancelled: 5,
    totalOperatingExpenses: 1831680,
    cashAndBankBalance: 20023104,
    totalActiveCustomers: 266,
    newCustomersAcquired: 16,
    customersChurned: 5,
    salesMarketingSpend: 448000,
    leadsGenerated: 176,
    leadsQualified: 109,
    demosCompleted: 59,
    dealsClosedWon: 16,
    npsScore: 53,
    headcount: 37,
    employeesExited: 0,
    openRoles: 5,
    grossMarginAssumption: 0.8,
  },
  {
    month: "Mar-26",
    activeSubscriptions: 273,
    monthlySubscriptionCost: 5000,
    newSubscriptionsStarted: 16,
    subscriptionsDowngradedMrrLost: 7191,
    subscriptionsCancelled: 5,
    totalOperatingExpenses: 1941581,
    cashAndBankBalance: 19446736,
    totalActiveCustomers: null,
    newCustomersAcquired: null,
    customersChurned: null,
    salesMarketingSpend: 500000,
    leadsGenerated: 20,
    leadsQualified: 5,
    demosCompleted: 5,
    dealsClosedWon: 5,
    npsScore: 54,
    headcount: 10,
    employeesExited: 0,
    openRoles: 5,
    grossMarginAssumption: 0.8,
  },
  {
    month: "Apr-26",
    activeSubscriptions: 280,
    monthlySubscriptionCost: 5000,
    newSubscriptionsStarted: 17,
    subscriptionsDowngradedMrrLost: 7622,
    subscriptionsCancelled: 6,
    totalOperatingExpenses: 2058075,
    cashAndBankBalance: 18804720,
    totalActiveCustomers: null,
    newCustomersAcquired: null,
    customersChurned: null,
    salesMarketingSpend: 550000,
    leadsGenerated: 30,
    leadsQualified: 10,
    demosCompleted: 10,
    dealsClosedWon: 10,
    npsScore: 55,
    headcount: 10,
    employeesExited: 1,
    openRoles: 5,
    grossMarginAssumption: 0.8,
  },
  {
    month: "May-26",
    activeSubscriptions: 287,
    monthlySubscriptionCost: 5000,
    newSubscriptionsStarted: 17,
    subscriptionsDowngradedMrrLost: 8080,
    subscriptionsCancelled: 6,
    totalOperatingExpenses: 2181561,
    cashAndBankBalance: 18091250,
    totalActiveCustomers: null,
    newCustomersAcquired: null,
    customersChurned: null,
    salesMarketingSpend: 550000,
    leadsGenerated: 30,
    leadsQualified: 15,
    demosCompleted: 15,
    dealsClosedWon: 15,
    npsScore: 52,
    headcount: 15,
    employeesExited: 0,
    openRoles: 5,
    grossMarginAssumption: 0.8,
  },
  {
    month: "Jun-26",
    activeSubscriptions: 294,
    monthlySubscriptionCost: 5000,
    newSubscriptionsStarted: 18,
    subscriptionsDowngradedMrrLost: 8565,
    subscriptionsCancelled: 6,
    totalOperatingExpenses: 2312454,
    cashAndBankBalance: 17300077,
    totalActiveCustomers: null,
    newCustomersAcquired: null,
    customersChurned: null,
    salesMarketingSpend: 550000,
    leadsGenerated: 40,
    leadsQualified: 20,
    demosCompleted: 20,
    dealsClosedWon: 20,
    npsScore: 53,
    headcount: 15,
    employeesExited: 0,
    openRoles: 5,
    grossMarginAssumption: 0.8,
  },
  {
    month: "Jul-26",
    activeSubscriptions: 302,
    monthlySubscriptionCost: 5000,
    newSubscriptionsStarted: 18,
    subscriptionsDowngradedMrrLost: 9079,
    subscriptionsCancelled: 6,
    totalOperatingExpenses: 2451200,
    cashAndBankBalance: 16424430,
    totalActiveCustomers: null,
    newCustomersAcquired: null,
    customersChurned: null,
    salesMarketingSpend: 550000,
    leadsGenerated: 10,
    leadsQualified: 10,
    demosCompleted: 10,
    dealsClosedWon: 10,
    npsScore: 54,
    headcount: 15,
    employeesExited: 1,
    openRoles: 4,
    grossMarginAssumption: 0.8,
  },
  {
    month: "Aug-26",
    activeSubscriptions: 309,
    monthlySubscriptionCost: 5000,
    newSubscriptionsStarted: 19,
    subscriptionsDowngradedMrrLost: 9623,
    subscriptionsCancelled: 6,
    totalOperatingExpenses: 2598273,
    cashAndBankBalance: 15457022,
    totalActiveCustomers: null,
    newCustomersAcquired: null,
    customersChurned: null,
    salesMarketingSpend: 550000,
    leadsGenerated: 20,
    leadsQualified: 15,
    demosCompleted: 0,
    dealsClosedWon: 0,
    npsScore: 55,
    headcount: 15,
    employeesExited: 0,
    openRoles: 4,
    grossMarginAssumption: 0.8,
  },
  {
    month: "Sep-26",
    activeSubscriptions: 317,
    monthlySubscriptionCost: 5000,
    newSubscriptionsStarted: 19,
    subscriptionsDowngradedMrrLost: 10201,
    subscriptionsCancelled: 6,
    totalOperatingExpenses: 2754170,
    cashAndBankBalance: 14389995,
    totalActiveCustomers: null,
    newCustomersAcquired: null,
    customersChurned: null,
    salesMarketingSpend: 550000,
    leadsGenerated: 30,
    leadsQualified: 10,
    demosCompleted: 10,
    dealsClosedWon: 10,
    npsScore: 52,
    headcount: 15,
    employeesExited: 0,
    openRoles: 4,
    grossMarginAssumption: 0.8,
  },
  {
    month: "Oct-26",
    activeSubscriptions: 325,
    monthlySubscriptionCost: 5000,
    newSubscriptionsStarted: 20,
    subscriptionsDowngradedMrrLost: 10813,
    subscriptionsCancelled: 6,
    totalOperatingExpenses: 2919420,
    cashAndBankBalance: 13214874,
    totalActiveCustomers: null,
    newCustomersAcquired: null,
    customersChurned: null,
    salesMarketingSpend: 550000,
    leadsGenerated: 40,
    leadsQualified: 10,
    demosCompleted: 0,
    dealsClosedWon: 0,
    npsScore: 53,
    headcount: 15,
    employeesExited: 1,
    openRoles: 4,
    grossMarginAssumption: 0.8,
  },
  {
    month: "Nov-26",
    activeSubscriptions: 333,
    monthlySubscriptionCost: 5000,
    newSubscriptionsStarted: 20,
    subscriptionsDowngradedMrrLost: 11461,
    subscriptionsCancelled: 7,
    totalOperatingExpenses: 3094585,
    cashAndBankBalance: 11922551,
    totalActiveCustomers: null,
    newCustomersAcquired: null,
    customersChurned: null,
    salesMarketingSpend: 550000,
    leadsGenerated: 10,
    leadsQualified: 10,
    demosCompleted: 10,
    dealsClosedWon: 10,
    npsScore: 54,
    headcount: 15,
    employeesExited: 0,
    openRoles: 4,
    grossMarginAssumption: 0.8,
  },
  {
    month: "Dec-26",
    activeSubscriptions: 341,
    monthlySubscriptionCost: 5000,
    newSubscriptionsStarted: 20,
    subscriptionsDowngradedMrrLost: 12149,
    subscriptionsCancelled: 7,
    totalOperatingExpenses: 3280260,
    cashAndBankBalance: 10503167,
    totalActiveCustomers: null,
    newCustomersAcquired: null,
    customersChurned: null,
    salesMarketingSpend: 550000,
    leadsGenerated: 20,
    leadsQualified: 10,
    demosCompleted: 10,
    dealsClosedWon: 10,
    npsScore: 55,
    headcount: 15,
    employeesExited: 0,
    openRoles: 4,
    grossMarginAssumption: 0.8,
  },
];

export const SEED_COMPLIANCE = [
  {
    id: "gst",
    name: "GST · GSTR-3B",
    status: "upcoming" as const,
    dueDate: "2026-07-20",
    daysRemaining: 31,
  },
  {
    id: "tds",
    name: "TDS · Monthly deposit",
    status: "upcoming" as const,
    dueDate: "2026-07-07",
    daysRemaining: 18,
  },
  {
    id: "roc",
    name: "ROC · Annual filing",
    status: "healthy" as const,
    dueDate: "2026-09-30",
    daysRemaining: 103,
  },
  {
    id: "pf",
    name: "PF / ESI · Challan",
    status: "healthy" as const,
    dueDate: "2026-07-15",
    daysRemaining: 26,
  },
];

export function getDefaultFounderAnalyticsState() {
  return {
    reportingMonth: "Jun-26" as const,
    months: SEED_RAW_INPUTS,
    compliance: SEED_COMPLIANCE,
    updatedAt: new Date().toISOString(),
  };
}
