import type { EntityType, Frequency } from "./types";

/** One row from the master compliance Excel — source of truth */
export interface ComplianceSheetRow {
  index: number;
  domain: string;
  description: string;
  complianceCategory: string;
  compliance: string;
  frequency: Frequency;
  weightage: number;
  evidence: string;
  /** Calendar routing — derived from frequency + statutory due dates */
  dueLogic: string;
  /** Entity types this row applies to (empty = none until matrix assigns) */
  entityTypes: EntityType[];
}

/**
 * Master compliance sheet — 62 rows for Private Limited.
 * Do not hardcode compliance names elsewhere; import from here.
 */
export const COMPLIANCE_SHEET: ComplianceSheetRow[] = [
  { index: 1, domain: "Corporate Governance", description: "MCA & Board Compliance", complianceCategory: "ROC Compliance", compliance: "Annual ROC Filing", frequency: "Annual", weightage: 100, evidence: "ROC Acknowledgement", dueLogic: "annual_fy_end", entityTypes: ["private_limited"] },
  { index: 2, domain: "Corporate Governance", description: "MCA & Board Compliance", complianceCategory: "ROC Compliance", compliance: "Financial Statement Filing", frequency: "Annual", weightage: 100, evidence: "MCA Filing Receipt", dueLogic: "annual_sep_30", entityTypes: ["private_limited"] },
  { index: 3, domain: "Corporate Governance", description: "MCA & Board Compliance", complianceCategory: "ROC Compliance", compliance: "Director KYC", frequency: "Annual", weightage: 75, evidence: "Director KYC Submission", dueLogic: "annual_fy_end", entityTypes: ["private_limited"] },
  { index: 4, domain: "Corporate Governance", description: "MCA & Board Compliance", complianceCategory: "ROC Compliance", compliance: "Registered Office Compliance", frequency: "Annual", weightage: 75, evidence: "Utility Bill / Lease Agreement", dueLogic: "annual_fy_end", entityTypes: ["private_limited"] },
  { index: 5, domain: "Corporate Governance", description: "MCA & Board Compliance", complianceCategory: "Board Governance", compliance: "Board Meeting Conduct", frequency: "Quarterly", weightage: 100, evidence: "Board Meeting Minutes", dueLogic: "quarterly_fy", entityTypes: ["private_limited"] },
  { index: 6, domain: "Corporate Governance", description: "MCA & Board Compliance", complianceCategory: "Board Governance", compliance: "Board Resolution Approval", frequency: "Quarterly", weightage: 75, evidence: "Approved Resolution", dueLogic: "quarterly_fy", entityTypes: ["private_limited"] },
  { index: 7, domain: "Corporate Governance", description: "MCA & Board Compliance", complianceCategory: "Board Governance", compliance: "Director Attendance Review", frequency: "Quarterly", weightage: 50, evidence: "Attendance Register", dueLogic: "quarterly_fy", entityTypes: ["private_limited"] },
  { index: 8, domain: "Corporate Governance", description: "MCA & Board Compliance", complianceCategory: "Governance", compliance: "Conflict of Interest Declaration", frequency: "Annual", weightage: 75, evidence: "Signed Declaration", dueLogic: "annual_fy_end", entityTypes: ["private_limited"] },
  { index: 9, domain: "Corporate Governance", description: "MCA & Board Compliance", complianceCategory: "Governance", compliance: "Related Party Transaction Review", frequency: "Quarterly", weightage: 100, evidence: "RPT Register", dueLogic: "quarterly_fy", entityTypes: ["private_limited"] },
  { index: 10, domain: "Corporate Governance", description: "MCA & Board Compliance", complianceCategory: "Governance", compliance: "Statutory Registers Review", frequency: "Annual", weightage: 75, evidence: "Updated Registers", dueLogic: "annual_fy_end", entityTypes: ["private_limited"] },
  { index: 11, domain: "Corporate Governance", description: "MCA & Board Compliance", complianceCategory: "Share Capital", compliance: "Shareholder Register Review", frequency: "Annual", weightage: 75, evidence: "Register Copy", dueLogic: "annual_fy_end", entityTypes: ["private_limited"] },
  { index: 12, domain: "Corporate Governance", description: "MCA & Board Compliance", complianceCategory: "Share Capital", compliance: "Share Allotment Filing", frequency: "Event Based", weightage: 100, evidence: "MCA Filing", dueLogic: "event_based", entityTypes: ["private_limited"] },
  { index: 13, domain: "Corporate Governance", description: "MCA & Board Compliance", complianceCategory: "Share Capital", compliance: "Share Transfer Compliance", frequency: "Event Based", weightage: 100, evidence: "Transfer Documents", dueLogic: "event_based", entityTypes: ["private_limited"] },
  { index: 14, domain: "Corporate Governance", description: "MCA & Board Compliance", complianceCategory: "Governance", compliance: "Beneficial Ownership Declaration", frequency: "Annual", weightage: 75, evidence: "Declaration Form", dueLogic: "annual_fy_end", entityTypes: ["private_limited"] },

  { index: 15, domain: "Taxation", description: "GST Compliance", complianceCategory: "GST", compliance: "GST Registration Review", frequency: "Annual", weightage: 100, evidence: "GST Certificate", dueLogic: "annual_fy_end", entityTypes: ["private_limited"] },
  { index: 16, domain: "Taxation", description: "GST Compliance", complianceCategory: "GST", compliance: "GSTR-1 Filing", frequency: "Monthly", weightage: 100, evidence: "GST Return", dueLogic: "monthly_13th", entityTypes: ["private_limited"] },
  { index: 17, domain: "Taxation", description: "GST Compliance", complianceCategory: "GST", compliance: "GSTR-3B Filing", frequency: "Monthly", weightage: 100, evidence: "GST Return", dueLogic: "monthly_11th", entityTypes: ["private_limited"] },
  { index: 18, domain: "Taxation", description: "GST Compliance", complianceCategory: "GST", compliance: "GST Reconciliation", frequency: "Monthly", weightage: 75, evidence: "Reconciliation Report", dueLogic: "monthly_last_day", entityTypes: ["private_limited"] },
  { index: 19, domain: "Taxation", description: "GST Compliance", complianceCategory: "GST", compliance: "GST Annual Return", frequency: "Annual", weightage: 100, evidence: "Annual GST Filing", dueLogic: "annual_fy_end", entityTypes: ["private_limited"] },
  { index: 20, domain: "Taxation", description: "GST Compliance", complianceCategory: "GST", compliance: "Input Tax Credit Validation", frequency: "Monthly", weightage: 75, evidence: "ITC Report", dueLogic: "monthly_last_day", entityTypes: ["private_limited"] },
  { index: 21, domain: "Taxation", description: "Direct Tax", complianceCategory: "TDS", compliance: "TDS Deduction Validation", frequency: "Monthly", weightage: 100, evidence: "TDS Register", dueLogic: "monthly_last_day", entityTypes: ["private_limited"] },
  { index: 22, domain: "Taxation", description: "Direct Tax", complianceCategory: "TDS", compliance: "TDS Deposit", frequency: "Monthly", weightage: 100, evidence: "Challan", dueLogic: "monthly_7th", entityTypes: ["private_limited"] },
  { index: 23, domain: "Taxation", description: "Direct Tax", complianceCategory: "TDS", compliance: "TDS Return Filing", frequency: "Quarterly", weightage: 100, evidence: "TDS Return", dueLogic: "quarterly_end_31st", entityTypes: ["private_limited"] },
  { index: 24, domain: "Taxation", description: "Direct Tax", complianceCategory: "TDS", compliance: "Form 16 Issuance", frequency: "Annual", weightage: 75, evidence: "Form 16", dueLogic: "annual_fy_end", entityTypes: ["private_limited"] },
  { index: 25, domain: "Taxation", description: "Direct Tax", complianceCategory: "Income Tax", compliance: "Income Tax Return", frequency: "Annual", weightage: 100, evidence: "ITR Acknowledgement", dueLogic: "annual_oct_31", entityTypes: ["private_limited"] },
  { index: 26, domain: "Taxation", description: "Direct Tax", complianceCategory: "Income Tax", compliance: "Advance Tax Payment", frequency: "Quarterly", weightage: 75, evidence: "Challan", dueLogic: "quarterly_fy", entityTypes: ["private_limited"] },
  { index: 27, domain: "Taxation", description: "Direct Tax", complianceCategory: "Income Tax", compliance: "Tax Provision Review", frequency: "Quarterly", weightage: 75, evidence: "Tax Computation", dueLogic: "quarterly_fy", entityTypes: ["private_limited"] },

  { index: 28, domain: "Human Resource Compliance", description: "Labour Compliance", complianceCategory: "Employee Lifecycle", compliance: "Offer Letter Issuance", frequency: "Event Based", weightage: 50, evidence: "Offer Letter", dueLogic: "event_based", entityTypes: ["private_limited"] },
  { index: 29, domain: "Human Resource Compliance", description: "Labour Compliance", complianceCategory: "Employee Lifecycle", compliance: "Employment Agreement", frequency: "Event Based", weightage: 75, evidence: "Signed Agreement", dueLogic: "event_based", entityTypes: ["private_limited"] },
  { index: 30, domain: "Human Resource Compliance", description: "Labour Compliance", complianceCategory: "Employee Lifecycle", compliance: "NDA Execution", frequency: "Event Based", weightage: 50, evidence: "Signed NDA", dueLogic: "event_based", entityTypes: ["private_limited"] },
  { index: 31, domain: "Human Resource Compliance", description: "Labour Compliance", complianceCategory: "Employee Lifecycle", compliance: "Background Verification", frequency: "Event Based", weightage: 75, evidence: "BGV Report", dueLogic: "event_based", entityTypes: ["private_limited"] },
  { index: 32, domain: "Human Resource Compliance", description: "Labour Compliance", complianceCategory: "Payroll", compliance: "Payroll Processing", frequency: "Monthly", weightage: 75, evidence: "Payroll Register", dueLogic: "monthly_last_day", entityTypes: ["private_limited"] },
  { index: 33, domain: "Human Resource Compliance", description: "Labour Compliance", complianceCategory: "Payroll", compliance: "Salary Disbursement", frequency: "Monthly", weightage: 75, evidence: "Bank Advice", dueLogic: "monthly_last_day", entityTypes: ["private_limited"] },
  { index: 34, domain: "Human Resource Compliance", description: "Labour Compliance", complianceCategory: "Payroll", compliance: "Payroll Reconciliation", frequency: "Monthly", weightage: 75, evidence: "Reconciliation Report", dueLogic: "monthly_last_day", entityTypes: ["private_limited"] },
  { index: 35, domain: "Human Resource Compliance", description: "Labour Compliance", complianceCategory: "PF Compliance", compliance: "PF Registration Review", frequency: "Annual", weightage: 75, evidence: "PF Registration", dueLogic: "annual_fy_end", entityTypes: ["private_limited"] },
  { index: 36, domain: "Human Resource Compliance", description: "Labour Compliance", complianceCategory: "PF Compliance", compliance: "PF Deposit", frequency: "Monthly", weightage: 100, evidence: "PF Challan", dueLogic: "monthly_15th", entityTypes: ["private_limited"] },
  { index: 37, domain: "Human Resource Compliance", description: "Labour Compliance", complianceCategory: "PF Compliance", compliance: "PF Return Filing", frequency: "Monthly", weightage: 100, evidence: "PF Return", dueLogic: "monthly_15th", entityTypes: ["private_limited"] },
  { index: 38, domain: "Human Resource Compliance", description: "Labour Compliance", complianceCategory: "ESI Compliance", compliance: "ESI Deposit", frequency: "Monthly", weightage: 100, evidence: "ESI Challan", dueLogic: "monthly_15th", entityTypes: ["private_limited"] },
  { index: 39, domain: "Human Resource Compliance", description: "Labour Compliance", complianceCategory: "ESI Compliance", compliance: "ESI Return Filing", frequency: "Monthly", weightage: 100, evidence: "ESI Filing", dueLogic: "monthly_15th", entityTypes: ["private_limited"] },
  { index: 40, domain: "Human Resource Compliance", description: "Labour Compliance", complianceCategory: "POSH", compliance: "POSH Policy Review", frequency: "Annual", weightage: 75, evidence: "Approved Policy", dueLogic: "annual_fy_end", entityTypes: ["private_limited"] },
  { index: 41, domain: "Human Resource Compliance", description: "Labour Compliance", complianceCategory: "POSH", compliance: "POSH Committee Review", frequency: "Annual", weightage: 75, evidence: "Committee Notification", dueLogic: "annual_fy_end", entityTypes: ["private_limited"] },
  { index: 42, domain: "Human Resource Compliance", description: "Labour Compliance", complianceCategory: "POSH", compliance: "POSH Awareness Training", frequency: "Annual", weightage: 50, evidence: "Training Records", dueLogic: "annual_fy_end", entityTypes: ["private_limited"] },

  { index: 43, domain: "Legal Compliance", description: "Contract Management", complianceCategory: "Founder Governance", compliance: "Founder Agreement Review", frequency: "Annual", weightage: 75, evidence: "Signed Agreement", dueLogic: "annual_fy_end", entityTypes: ["private_limited"] },
  { index: 44, domain: "Legal Compliance", description: "Contract Management", complianceCategory: "Shareholder Governance", compliance: "Shareholder Agreement Review", frequency: "Annual", weightage: 75, evidence: "Agreement Copy", dueLogic: "annual_fy_end", entityTypes: ["private_limited"] },
  { index: 45, domain: "Legal Compliance", description: "Contract Management", complianceCategory: "Contracts", compliance: "Customer Contract Review", frequency: "Annual", weightage: 50, evidence: "Contract Repository", dueLogic: "annual_fy_end", entityTypes: ["private_limited"] },
  { index: 46, domain: "Legal Compliance", description: "Contract Management", complianceCategory: "Contracts", compliance: "Vendor Contract Review", frequency: "Annual", weightage: 50, evidence: "Contract Repository", dueLogic: "annual_fy_end", entityTypes: ["private_limited"] },
  { index: 47, domain: "Legal Compliance", description: "Contract Management", complianceCategory: "NDA", compliance: "NDA Repository Review", frequency: "Annual", weightage: 50, evidence: "NDA Register", dueLogic: "annual_fy_end", entityTypes: ["private_limited"] },
  { index: 48, domain: "Legal Compliance", description: "Intellectual Property", complianceCategory: "Trademark", compliance: "Trademark Registration Review", frequency: "Annual", weightage: 75, evidence: "Trademark Certificate", dueLogic: "annual_fy_end", entityTypes: ["private_limited"] },
  { index: 49, domain: "Legal Compliance", description: "Intellectual Property", complianceCategory: "Copyright", compliance: "Copyright Protection Review", frequency: "Annual", weightage: 50, evidence: "Registration Certificate", dueLogic: "annual_fy_end", entityTypes: ["private_limited"] },
  { index: 50, domain: "Legal Compliance", description: "Intellectual Property", complianceCategory: "IP Assignment", compliance: "Employee IP Assignment Review", frequency: "Annual", weightage: 75, evidence: "Signed Assignment", dueLogic: "annual_fy_end", entityTypes: ["private_limited"] },
  { index: 51, domain: "Legal Compliance", description: "Litigation", complianceCategory: "Legal Risk", compliance: "Litigation Register Review", frequency: "Quarterly", weightage: 75, evidence: "Litigation Register", dueLogic: "quarterly_fy", entityTypes: ["private_limited"] },

  { index: 52, domain: "Information Security", description: "ISO 27001", complianceCategory: "Governance", compliance: "Information Security Policy Review", frequency: "Annual", weightage: 100, evidence: "Approved Policy", dueLogic: "annual_fy_end", entityTypes: ["private_limited"] },
  { index: 53, domain: "Information Security", description: "ISO 27001", complianceCategory: "Governance", compliance: "Information Security Objectives Review", frequency: "Annual", weightage: 75, evidence: "Objectives Register", dueLogic: "annual_fy_end", entityTypes: ["private_limited"] },
  { index: 54, domain: "Information Security", description: "ISO 27001", complianceCategory: "Access Control", compliance: "User Access Review", frequency: "Quarterly", weightage: 100, evidence: "Access Review Report", dueLogic: "quarterly_fy", entityTypes: ["private_limited"] },
  { index: 55, domain: "Information Security", description: "ISO 27001", complianceCategory: "Access Control", compliance: "Privileged Access Review", frequency: "Quarterly", weightage: 100, evidence: "PAM Review", dueLogic: "quarterly_fy", entityTypes: ["private_limited"] },
  { index: 56, domain: "Information Security", description: "ISO 27001", complianceCategory: "Asset Management", compliance: "Asset Inventory Review", frequency: "Quarterly", weightage: 75, evidence: "Asset Register", dueLogic: "quarterly_fy", entityTypes: ["private_limited"] },
  { index: 57, domain: "Information Security", description: "ISO 27001", complianceCategory: "Vulnerability Management", compliance: "Vulnerability Assessment", frequency: "Quarterly", weightage: 100, evidence: "VA Report", dueLogic: "quarterly_fy", entityTypes: ["private_limited"] },
  { index: 58, domain: "Information Security", description: "ISO 27001", complianceCategory: "Vulnerability Management", compliance: "Penetration Testing", frequency: "Annual", weightage: 100, evidence: "PT Report", dueLogic: "annual_fy_end", entityTypes: ["private_limited"] },
  { index: 59, domain: "Information Security", description: "ISO 27001", complianceCategory: "Patch Management", compliance: "Critical Patch Review", frequency: "Monthly", weightage: 75, evidence: "Patch Report", dueLogic: "monthly_last_day", entityTypes: ["private_limited"] },
  { index: 60, domain: "Information Security", description: "ISO 27001", complianceCategory: "Incident Management", compliance: "Security Incident Review", frequency: "Monthly", weightage: 100, evidence: "Incident Register", dueLogic: "monthly_last_day", entityTypes: ["private_limited"] },
  { index: 61, domain: "Information Security", description: "ISO 27001", complianceCategory: "Backup Management", compliance: "Backup Verification", frequency: "Monthly", weightage: 75, evidence: "Backup Logs", dueLogic: "monthly_last_day", entityTypes: ["private_limited"] },
  { index: 62, domain: "Information Security", description: "ISO 27001", complianceCategory: "Awareness", compliance: "Security Awareness Training", frequency: "Annual", weightage: 75, evidence: "Training Record", dueLogic: "annual_fy_end", entityTypes: ["private_limited"] },
];
