import { formatDateLabel } from "./date-utils";
import type { NotificationType } from "./types";

/** Production WhatsApp message templates — backend only, never shown in UI */
export function buildComplianceMessage(
  type: NotificationType,
  complianceName: string,
  dueDate: string
): string {
  const label = formatDateLabel(dueDate);

  switch (type) {
    case "reminder_10d":
      return [
        "🔔 ComplyOS Reminder",
        "",
        `"${complianceName}" is due on ${label}.`,
        "",
        "Please upload evidence before the due date.",
      ].join("\n");
    case "reminder_3d":
      return [
        "⚠ Upcoming Compliance",
        "",
        `"${complianceName}" is due in 3 days.`,
        "",
        "Immediate attention recommended.",
      ].join("\n");
    case "due_today":
      return [
        "⚠ Compliance Due Today",
        "",
        `"${complianceName}" is due today.`,
        "",
        "Please complete and upload evidence.",
      ].join("\n");
    case "overdue":
      return [
        "❗ Critical Compliance Alert",
        "",
        `"${complianceName}" is overdue.`,
        "",
        `Due Date: ${label}`,
        "",
        "Immediate action required.",
      ].join("\n");
    default:
      return `ComplyOS: ${complianceName} — ${label}`;
  }
}

export function buildExecutiveSummaryMessage(summary: {
  overallScore: number;
  overdue: string[];
  upcoming: string[];
  criticalItems: number;
  pendingItems: number;
  recentActivity: string[];
}): string {
  const lines = [
    "📊 ComplyOS Executive Summary",
    "",
    "Overall Compliance Score",
    `${summary.overallScore}%`,
    "",
    "━━━━━━━━━━━━━━",
    "",
    "🔴 Overdue",
    "",
    ...(summary.overdue.length
      ? summary.overdue.map((n) => `• ${n}`)
      : ["• None"]),
    "",
    "━━━━━━━━━━━━━━",
    "",
    "🟡 Upcoming",
    "",
    ...(summary.upcoming.length
      ? summary.upcoming.map((n) => `• ${n}`)
      : ["• None"]),
    "",
    "━━━━━━━━━━━━━━",
    "",
    "⚠ Critical Items",
    String(summary.criticalItems),
    "",
    "Pending Items",
    String(summary.pendingItems),
    "",
    "━━━━━━━━━━━━━━",
    "",
    "Recent Activity",
    "",
    ...(summary.recentActivity.length
      ? summary.recentActivity.map((a) => `• ${a}`)
      : ["• No recent activity"]),
    "",
    "━━━━━━━━━━━━━━",
    "",
    "Generated by ComplyOS",
  ];
  return lines.join("\n");
}
