/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MsmeRouteImport } from './routes/msme'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ItServiceRouteImport } from './routes/it-service'
import { Route as ItRouteImport } from './routes/it'
import { Route as HealthcareRouteImport } from './routes/healthcare'
import { Route as GovtRouteImport } from './routes/govt'
import { Route as FintechRouteImport } from './routes/fintech'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PartnerIndexRouteImport } from './routes/partner/index'
import { Route as FounderIndexRouteImport } from './routes/founder/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as PartnerTemplatesRouteImport } from './routes/partner/templates'
import { Route as PartnerFeedRouteImport } from './routes/partner/feed'
import { Route as PartnerEarningsRouteImport } from './routes/partner/earnings'
import { Route as PartnerDeliverablesRouteImport } from './routes/partner/deliverables'
import { Route as PartnerChatRouteImport } from './routes/partner/chat'
import { Route as PartnerAssignmentsRouteImport } from './routes/partner/assignments'
import { Route as ItServiceVendorRouteImport } from './routes/it-service/vendor'
import { Route as ItServiceTaxationRouteImport } from './routes/it-service/taxation'
import { Route as ItServiceSettingsRouteImport } from './routes/it-service/settings'
import { Route as ItServiceSecurityRouteImport } from './routes/it-service/security'
import { Route as ItServiceReportsRouteImport } from './routes/it-service/reports'
import { Route as ItServiceProfileRouteImport } from './routes/it-service/profile'
import { Route as ItServicePrivacyRouteImport } from './routes/it-service/privacy'
import { Route as ItServiceOnboardingRouteImport } from './routes/it-service/onboarding'
import { Route as ItServiceLoginRouteImport } from './routes/it-service/login'
import { Route as ItServiceLegalRouteImport } from './routes/it-service/legal'
import { Route as ItServiceInsightsRouteImport } from './routes/it-service/insights'
import { Route as ItServiceHrRouteImport } from './routes/it-service/hr'
import { Route as ItServiceGovernanceRouteImport } from './routes/it-service/governance'
import { Route as ItServiceFinancialRouteImport } from './routes/it-service/financial'
import { Route as ItServiceEvidenceRouteImport } from './routes/it-service/evidence'
import { Route as ItServiceDashboardRouteImport } from './routes/it-service/dashboard'
import { Route as ItServiceCalendarRouteImport } from './routes/it-service/calendar'
import { Route as FounderVaultRouteImport } from './routes/founder/vault'
import { Route as FounderRegulatoryRouteImport } from './routes/founder/regulatory'
import { Route as FounderProfileRouteImport } from './routes/founder/profile'
import { Route as FounderPayrollRouteImport } from './routes/founder/payroll'
import { Route as FounderKpisRouteImport } from './routes/founder/kpis'
import { Route as FounderDataCenterRouteImport } from './routes/founder/data-center'
import { Route as FounderCalendarRouteImport } from './routes/founder/calendar'
import { Route as FounderBillingRouteImport } from './routes/founder/billing'
import { Route as AdminSlaRouteImport } from './routes/admin/sla'
import { Route as AdminPartnersRouteImport } from './routes/admin/partners'
import { Route as AdminOrdersRouteImport } from './routes/admin/orders'
import { Route as AdminIntakeRouteImport } from './routes/admin/intake'
import { Route as AdminCustomersRouteImport } from './routes/admin/customers'
import { Route as AdminCatalogueRouteImport } from './routes/admin/catalogue'
import { Route as AdminBiRouteImport } from './routes/admin/bi'
import { Route as FounderOrdersIndexRouteImport } from './routes/founder/orders.index'
import { Route as FounderMarketplaceIndexRouteImport } from './routes/founder/marketplace.index'
import { Route as FounderBooksIndexRouteImport } from './routes/founder/books.index'
import { Route as FounderOrdersOrderIdRouteImport } from './routes/founder/orders_.$orderId'
import { Route as FounderBooksReportsRouteImport } from './routes/founder/books.reports'
import { Route as FounderBooksInvoicesRouteImport } from './routes/founder/books.invoices'
import { Route as FounderBooksExpensesRouteImport } from './routes/founder/books.expenses'
import { Route as FounderBooksConnectorsRouteImport } from './routes/founder/books.connectors'
import { Route as FounderBooksBankingRouteImport } from './routes/founder/books.banking'
import { Route as FounderAiGrowthRouteImport } from './routes/founder/ai.growth'
import { Route as FounderAiFinanceRouteImport } from './routes/founder/ai.finance'
import { Route as FounderAiComplianceRouteImport } from './routes/founder/ai.compliance'
import { Route as FounderMarketplaceOrderServiceIdRouteImport } from './routes/founder/marketplace_.order.$serviceId'
import { Route as ApiPublicZohoCallbackRouteImport } from './routes/api/public/zoho/callback'

const MsmeRoute = MsmeRouteImport.update({
  id: '/msme',
  path: '/msme',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ItServiceRoute = ItServiceRouteImport.update({
  id: '/it-service',
  path: '/it-service',
  getParentRoute: () => rootRouteImport,
} as any)
const ItRoute = ItRouteImport.update({
  id: '/it',
  path: '/it',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthcareRoute = HealthcareRouteImport.update({
  id: '/healthcare',
  path: '/healthcare',
  getParentRoute: () => rootRouteImport,
} as any)
const GovtRoute = GovtRouteImport.update({
  id: '/govt',
  path: '/govt',
  getParentRoute: () => rootRouteImport,
} as any)
const FintechRoute = FintechRouteImport.update({
  id: '/fintech',
  path: '/fintech',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerIndexRoute = PartnerIndexRouteImport.update({
  id: '/partner/',
  path: '/partner/',
  getParentRoute: () => rootRouteImport,
} as any)
const FounderIndexRoute = FounderIndexRouteImport.update({
  id: '/founder/',
  path: '/founder/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerTemplatesRoute = PartnerTemplatesRouteImport.update({
  id: '/partner/templates',
  path: '/partner/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerFeedRoute = PartnerFeedRouteImport.update({
  id: '/partner/feed',
  path: '/partner/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerEarningsRoute = PartnerEarningsRouteImport.update({
  id: '/partner/earnings',
  path: '/partner/earnings',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerDeliverablesRoute = PartnerDeliverablesRouteImport.update({
  id: '/partner/deliverables',
  path: '/partner/deliverables',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerChatRoute = PartnerChatRouteImport.update({
  id: '/partner/chat',
  path: '/partner/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerAssignmentsRoute = PartnerAssignmentsRouteImport.update({
  id: '/partner/assignments',
  path: '/partner/assignments',
  getParentRoute: () => rootRouteImport,
} as any)
const ItServiceVendorRoute = ItServiceVendorRouteImport.update({
  id: '/vendor',
  path: '/vendor',
  getParentRoute: () => ItServiceRoute,
} as any)
const ItServiceTaxationRoute = ItServiceTaxationRouteImport.update({
  id: '/taxation',
  path: '/taxation',
  getParentRoute: () => ItServiceRoute,
} as any)
const ItServiceSettingsRoute = ItServiceSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ItServiceRoute,
} as any)
const ItServiceSecurityRoute = ItServiceSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => ItServiceRoute,
} as any)
const ItServiceReportsRoute = ItServiceReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => ItServiceRoute,
} as any)
const ItServiceProfileRoute = ItServiceProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ItServiceRoute,
} as any)
const ItServicePrivacyRoute = ItServicePrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => ItServiceRoute,
} as any)
const ItServiceOnboardingRoute = ItServiceOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => ItServiceRoute,
} as any)
const ItServiceLoginRoute = ItServiceLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => ItServiceRoute,
} as any)
const ItServiceLegalRoute = ItServiceLegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => ItServiceRoute,
} as any)
const ItServiceInsightsRoute = ItServiceInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => ItServiceRoute,
} as any)
const ItServiceHrRoute = ItServiceHrRouteImport.update({
  id: '/hr',
  path: '/hr',
  getParentRoute: () => ItServiceRoute,
} as any)
const ItServiceGovernanceRoute = ItServiceGovernanceRouteImport.update({
  id: '/governance',
  path: '/governance',
  getParentRoute: () => ItServiceRoute,
} as any)
const ItServiceFinancialRoute = ItServiceFinancialRouteImport.update({
  id: '/financial',
  path: '/financial',
  getParentRoute: () => ItServiceRoute,
} as any)
const ItServiceEvidenceRoute = ItServiceEvidenceRouteImport.update({
  id: '/evidence',
  path: '/evidence',
  getParentRoute: () => ItServiceRoute,
} as any)
const ItServiceDashboardRoute = ItServiceDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ItServiceRoute,
} as any)
const ItServiceCalendarRoute = ItServiceCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => ItServiceRoute,
} as any)
const FounderVaultRoute = FounderVaultRouteImport.update({
  id: '/founder/vault',
  path: '/founder/vault',
  getParentRoute: () => rootRouteImport,
} as any)
const FounderRegulatoryRoute = FounderRegulatoryRouteImport.update({
  id: '/founder/regulatory',
  path: '/founder/regulatory',
  getParentRoute: () => rootRouteImport,
} as any)
const FounderProfileRoute = FounderProfileRouteImport.update({
  id: '/founder/profile',
  path: '/founder/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const FounderPayrollRoute = FounderPayrollRouteImport.update({
  id: '/founder/payroll',
  path: '/founder/payroll',
  getParentRoute: () => rootRouteImport,
} as any)
const FounderKpisRoute = FounderKpisRouteImport.update({
  id: '/founder/kpis',
  path: '/founder/kpis',
  getParentRoute: () => rootRouteImport,
} as any)
const FounderDataCenterRoute = FounderDataCenterRouteImport.update({
  id: '/founder/data-center',
  path: '/founder/data-center',
  getParentRoute: () => rootRouteImport,
} as any)
const FounderCalendarRoute = FounderCalendarRouteImport.update({
  id: '/founder/calendar',
  path: '/founder/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const FounderBillingRoute = FounderBillingRouteImport.update({
  id: '/founder/billing',
  path: '/founder/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSlaRoute = AdminSlaRouteImport.update({
  id: '/admin/sla',
  path: '/admin/sla',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPartnersRoute = AdminPartnersRouteImport.update({
  id: '/admin/partners',
  path: '/admin/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/admin/orders',
  path: '/admin/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIntakeRoute = AdminIntakeRouteImport.update({
  id: '/admin/intake',
  path: '/admin/intake',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/admin/customers',
  path: '/admin/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCatalogueRoute = AdminCatalogueRouteImport.update({
  id: '/admin/catalogue',
  path: '/admin/catalogue',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBiRoute = AdminBiRouteImport.update({
  id: '/admin/bi',
  path: '/admin/bi',
  getParentRoute: () => rootRouteImport,
} as any)
const FounderOrdersIndexRoute = FounderOrdersIndexRouteImport.update({
  id: '/founder/orders/',
  path: '/founder/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const FounderMarketplaceIndexRoute = FounderMarketplaceIndexRouteImport.update({
  id: '/founder/marketplace/',
  path: '/founder/marketplace/',
  getParentRoute: () => rootRouteImport,
} as any)
const FounderBooksIndexRoute = FounderBooksIndexRouteImport.update({
  id: '/founder/books/',
  path: '/founder/books/',
  getParentRoute: () => rootRouteImport,
} as any)
const FounderOrdersOrderIdRoute = FounderOrdersOrderIdRouteImport.update({
  id: '/founder/orders_/$orderId',
  path: '/founder/orders/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const FounderBooksReportsRoute = FounderBooksReportsRouteImport.update({
  id: '/founder/books/reports',
  path: '/founder/books/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const FounderBooksInvoicesRoute = FounderBooksInvoicesRouteImport.update({
  id: '/founder/books/invoices',
  path: '/founder/books/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const FounderBooksExpensesRoute = FounderBooksExpensesRouteImport.update({
  id: '/founder/books/expenses',
  path: '/founder/books/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const FounderBooksConnectorsRoute = FounderBooksConnectorsRouteImport.update({
  id: '/founder/books/connectors',
  path: '/founder/books/connectors',
  getParentRoute: () => rootRouteImport,
} as any)
const FounderBooksBankingRoute = FounderBooksBankingRouteImport.update({
  id: '/founder/books/banking',
  path: '/founder/books/banking',
  getParentRoute: () => rootRouteImport,
} as any)
const FounderAiGrowthRoute = FounderAiGrowthRouteImport.update({
  id: '/founder/ai/growth',
  path: '/founder/ai/growth',
  getParentRoute: () => rootRouteImport,
} as any)
const FounderAiFinanceRoute = FounderAiFinanceRouteImport.update({
  id: '/founder/ai/finance',
  path: '/founder/ai/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const FounderAiComplianceRoute = FounderAiComplianceRouteImport.update({
  id: '/founder/ai/compliance',
  path: '/founder/ai/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const FounderMarketplaceOrderServiceIdRoute =
  FounderMarketplaceOrderServiceIdRouteImport.update({
    id: '/founder/marketplace_/order/$serviceId',
    path: '/founder/marketplace/order/$serviceId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicZohoCallbackRoute = ApiPublicZohoCallbackRouteImport.update({
  id: '/api/public/zoho/callback',
  path: '/api/public/zoho/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/fintech': typeof FintechRoute
  '/govt': typeof GovtRoute
  '/healthcare': typeof HealthcareRoute
  '/it': typeof ItRoute
  '/it-service': typeof ItServiceRouteWithChildren
  '/login': typeof LoginRoute
  '/msme': typeof MsmeRoute
  '/admin/bi': typeof AdminBiRoute
  '/admin/catalogue': typeof AdminCatalogueRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/intake': typeof AdminIntakeRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/partners': typeof AdminPartnersRoute
  '/admin/sla': typeof AdminSlaRoute
  '/founder/billing': typeof FounderBillingRoute
  '/founder/calendar': typeof FounderCalendarRoute
  '/founder/data-center': typeof FounderDataCenterRoute
  '/founder/kpis': typeof FounderKpisRoute
  '/founder/payroll': typeof FounderPayrollRoute
  '/founder/profile': typeof FounderProfileRoute
  '/founder/regulatory': typeof FounderRegulatoryRoute
  '/founder/vault': typeof FounderVaultRoute
  '/it-service/calendar': typeof ItServiceCalendarRoute
  '/it-service/dashboard': typeof ItServiceDashboardRoute
  '/it-service/evidence': typeof ItServiceEvidenceRoute
  '/it-service/financial': typeof ItServiceFinancialRoute
  '/it-service/governance': typeof ItServiceGovernanceRoute
  '/it-service/hr': typeof ItServiceHrRoute
  '/it-service/insights': typeof ItServiceInsightsRoute
  '/it-service/legal': typeof ItServiceLegalRoute
  '/it-service/login': typeof ItServiceLoginRoute
  '/it-service/onboarding': typeof ItServiceOnboardingRoute
  '/it-service/privacy': typeof ItServicePrivacyRoute
  '/it-service/profile': typeof ItServiceProfileRoute
  '/it-service/reports': typeof ItServiceReportsRoute
  '/it-service/security': typeof ItServiceSecurityRoute
  '/it-service/settings': typeof ItServiceSettingsRoute
  '/it-service/taxation': typeof ItServiceTaxationRoute
  '/it-service/vendor': typeof ItServiceVendorRoute
  '/partner/assignments': typeof PartnerAssignmentsRoute
  '/partner/chat': typeof PartnerChatRoute
  '/partner/deliverables': typeof PartnerDeliverablesRoute
  '/partner/earnings': typeof PartnerEarningsRoute
  '/partner/feed': typeof PartnerFeedRoute
  '/partner/templates': typeof PartnerTemplatesRoute
  '/admin/': typeof AdminIndexRoute
  '/founder/': typeof FounderIndexRoute
  '/partner/': typeof PartnerIndexRoute
  '/founder/ai/compliance': typeof FounderAiComplianceRoute
  '/founder/ai/finance': typeof FounderAiFinanceRoute
  '/founder/ai/growth': typeof FounderAiGrowthRoute
  '/founder/books/banking': typeof FounderBooksBankingRoute
  '/founder/books/connectors': typeof FounderBooksConnectorsRoute
  '/founder/books/expenses': typeof FounderBooksExpensesRoute
  '/founder/books/invoices': typeof FounderBooksInvoicesRoute
  '/founder/books/reports': typeof FounderBooksReportsRoute
  '/founder/orders/$orderId': typeof FounderOrdersOrderIdRoute
  '/founder/books/': typeof FounderBooksIndexRoute
  '/founder/marketplace/': typeof FounderMarketplaceIndexRoute
  '/founder/orders/': typeof FounderOrdersIndexRoute
  '/api/public/zoho/callback': typeof ApiPublicZohoCallbackRoute
  '/founder/marketplace/order/$serviceId': typeof FounderMarketplaceOrderServiceIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/fintech': typeof FintechRoute
  '/govt': typeof GovtRoute
  '/healthcare': typeof HealthcareRoute
  '/it': typeof ItRoute
  '/it-service': typeof ItServiceRouteWithChildren
  '/login': typeof LoginRoute
  '/msme': typeof MsmeRoute
  '/admin/bi': typeof AdminBiRoute
  '/admin/catalogue': typeof AdminCatalogueRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/intake': typeof AdminIntakeRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/partners': typeof AdminPartnersRoute
  '/admin/sla': typeof AdminSlaRoute
  '/founder/billing': typeof FounderBillingRoute
  '/founder/calendar': typeof FounderCalendarRoute
  '/founder/data-center': typeof FounderDataCenterRoute
  '/founder/kpis': typeof FounderKpisRoute
  '/founder/payroll': typeof FounderPayrollRoute
  '/founder/profile': typeof FounderProfileRoute
  '/founder/regulatory': typeof FounderRegulatoryRoute
  '/founder/vault': typeof FounderVaultRoute
  '/it-service/calendar': typeof ItServiceCalendarRoute
  '/it-service/dashboard': typeof ItServiceDashboardRoute
  '/it-service/evidence': typeof ItServiceEvidenceRoute
  '/it-service/financial': typeof ItServiceFinancialRoute
  '/it-service/governance': typeof ItServiceGovernanceRoute
  '/it-service/hr': typeof ItServiceHrRoute
  '/it-service/insights': typeof ItServiceInsightsRoute
  '/it-service/legal': typeof ItServiceLegalRoute
  '/it-service/login': typeof ItServiceLoginRoute
  '/it-service/onboarding': typeof ItServiceOnboardingRoute
  '/it-service/privacy': typeof ItServicePrivacyRoute
  '/it-service/profile': typeof ItServiceProfileRoute
  '/it-service/reports': typeof ItServiceReportsRoute
  '/it-service/security': typeof ItServiceSecurityRoute
  '/it-service/settings': typeof ItServiceSettingsRoute
  '/it-service/taxation': typeof ItServiceTaxationRoute
  '/it-service/vendor': typeof ItServiceVendorRoute
  '/partner/assignments': typeof PartnerAssignmentsRoute
  '/partner/chat': typeof PartnerChatRoute
  '/partner/deliverables': typeof PartnerDeliverablesRoute
  '/partner/earnings': typeof PartnerEarningsRoute
  '/partner/feed': typeof PartnerFeedRoute
  '/partner/templates': typeof PartnerTemplatesRoute
  '/admin': typeof AdminIndexRoute
  '/founder': typeof FounderIndexRoute
  '/partner': typeof PartnerIndexRoute
  '/founder/ai/compliance': typeof FounderAiComplianceRoute
  '/founder/ai/finance': typeof FounderAiFinanceRoute
  '/founder/ai/growth': typeof FounderAiGrowthRoute
  '/founder/books/banking': typeof FounderBooksBankingRoute
  '/founder/books/connectors': typeof FounderBooksConnectorsRoute
  '/founder/books/expenses': typeof FounderBooksExpensesRoute
  '/founder/books/invoices': typeof FounderBooksInvoicesRoute
  '/founder/books/reports': typeof FounderBooksReportsRoute
  '/founder/orders/$orderId': typeof FounderOrdersOrderIdRoute
  '/founder/books': typeof FounderBooksIndexRoute
  '/founder/marketplace': typeof FounderMarketplaceIndexRoute
  '/founder/orders': typeof FounderOrdersIndexRoute
  '/api/public/zoho/callback': typeof ApiPublicZohoCallbackRoute
  '/founder/marketplace/order/$serviceId': typeof FounderMarketplaceOrderServiceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/fintech': typeof FintechRoute
  '/govt': typeof GovtRoute
  '/healthcare': typeof HealthcareRoute
  '/it': typeof ItRoute
  '/it-service': typeof ItServiceRouteWithChildren
  '/login': typeof LoginRoute
  '/msme': typeof MsmeRoute
  '/admin/bi': typeof AdminBiRoute
  '/admin/catalogue': typeof AdminCatalogueRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/intake': typeof AdminIntakeRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/partners': typeof AdminPartnersRoute
  '/admin/sla': typeof AdminSlaRoute
  '/founder/billing': typeof FounderBillingRoute
  '/founder/calendar': typeof FounderCalendarRoute
  '/founder/data-center': typeof FounderDataCenterRoute
  '/founder/kpis': typeof FounderKpisRoute
  '/founder/payroll': typeof FounderPayrollRoute
  '/founder/profile': typeof FounderProfileRoute
  '/founder/regulatory': typeof FounderRegulatoryRoute
  '/founder/vault': typeof FounderVaultRoute
  '/it-service/calendar': typeof ItServiceCalendarRoute
  '/it-service/dashboard': typeof ItServiceDashboardRoute
  '/it-service/evidence': typeof ItServiceEvidenceRoute
  '/it-service/financial': typeof ItServiceFinancialRoute
  '/it-service/governance': typeof ItServiceGovernanceRoute
  '/it-service/hr': typeof ItServiceHrRoute
  '/it-service/insights': typeof ItServiceInsightsRoute
  '/it-service/legal': typeof ItServiceLegalRoute
  '/it-service/login': typeof ItServiceLoginRoute
  '/it-service/onboarding': typeof ItServiceOnboardingRoute
  '/it-service/privacy': typeof ItServicePrivacyRoute
  '/it-service/profile': typeof ItServiceProfileRoute
  '/it-service/reports': typeof ItServiceReportsRoute
  '/it-service/security': typeof ItServiceSecurityRoute
  '/it-service/settings': typeof ItServiceSettingsRoute
  '/it-service/taxation': typeof ItServiceTaxationRoute
  '/it-service/vendor': typeof ItServiceVendorRoute
  '/partner/assignments': typeof PartnerAssignmentsRoute
  '/partner/chat': typeof PartnerChatRoute
  '/partner/deliverables': typeof PartnerDeliverablesRoute
  '/partner/earnings': typeof PartnerEarningsRoute
  '/partner/feed': typeof PartnerFeedRoute
  '/partner/templates': typeof PartnerTemplatesRoute
  '/admin/': typeof AdminIndexRoute
  '/founder/': typeof FounderIndexRoute
  '/partner/': typeof PartnerIndexRoute
  '/founder/ai/compliance': typeof FounderAiComplianceRoute
  '/founder/ai/finance': typeof FounderAiFinanceRoute
  '/founder/ai/growth': typeof FounderAiGrowthRoute
  '/founder/books/banking': typeof FounderBooksBankingRoute
  '/founder/books/connectors': typeof FounderBooksConnectorsRoute
  '/founder/books/expenses': typeof FounderBooksExpensesRoute
  '/founder/books/invoices': typeof FounderBooksInvoicesRoute
  '/founder/books/reports': typeof FounderBooksReportsRoute
  '/founder/orders_/$orderId': typeof FounderOrdersOrderIdRoute
  '/founder/books/': typeof FounderBooksIndexRoute
  '/founder/marketplace/': typeof FounderMarketplaceIndexRoute
  '/founder/orders/': typeof FounderOrdersIndexRoute
  '/api/public/zoho/callback': typeof ApiPublicZohoCallbackRoute
  '/founder/marketplace_/order/$serviceId': typeof FounderMarketplaceOrderServiceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/fintech'
    | '/govt'
    | '/healthcare'
    | '/it'
    | '/it-service'
    | '/login'
    | '/msme'
    | '/admin/bi'
    | '/admin/catalogue'
    | '/admin/customers'
    | '/admin/intake'
    | '/admin/orders'
    | '/admin/partners'
    | '/admin/sla'
    | '/founder/billing'
    | '/founder/calendar'
    | '/founder/data-center'
    | '/founder/kpis'
    | '/founder/payroll'
    | '/founder/profile'
    | '/founder/regulatory'
    | '/founder/vault'
    | '/it-service/calendar'
    | '/it-service/dashboard'
    | '/it-service/evidence'
    | '/it-service/financial'
    | '/it-service/governance'
    | '/it-service/hr'
    | '/it-service/insights'
    | '/it-service/legal'
    | '/it-service/login'
    | '/it-service/onboarding'
    | '/it-service/privacy'
    | '/it-service/profile'
    | '/it-service/reports'
    | '/it-service/security'
    | '/it-service/settings'
    | '/it-service/taxation'
    | '/it-service/vendor'
    | '/partner/assignments'
    | '/partner/chat'
    | '/partner/deliverables'
    | '/partner/earnings'
    | '/partner/feed'
    | '/partner/templates'
    | '/admin/'
    | '/founder/'
    | '/partner/'
    | '/founder/ai/compliance'
    | '/founder/ai/finance'
    | '/founder/ai/growth'
    | '/founder/books/banking'
    | '/founder/books/connectors'
    | '/founder/books/expenses'
    | '/founder/books/invoices'
    | '/founder/books/reports'
    | '/founder/orders/$orderId'
    | '/founder/books/'
    | '/founder/marketplace/'
    | '/founder/orders/'
    | '/api/public/zoho/callback'
    | '/founder/marketplace/order/$serviceId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/fintech'
    | '/govt'
    | '/healthcare'
    | '/it'
    | '/it-service'
    | '/login'
    | '/msme'
    | '/admin/bi'
    | '/admin/catalogue'
    | '/admin/customers'
    | '/admin/intake'
    | '/admin/orders'
    | '/admin/partners'
    | '/admin/sla'
    | '/founder/billing'
    | '/founder/calendar'
    | '/founder/data-center'
    | '/founder/kpis'
    | '/founder/payroll'
    | '/founder/profile'
    | '/founder/regulatory'
    | '/founder/vault'
    | '/it-service/calendar'
    | '/it-service/dashboard'
    | '/it-service/evidence'
    | '/it-service/financial'
    | '/it-service/governance'
    | '/it-service/hr'
    | '/it-service/insights'
    | '/it-service/legal'
    | '/it-service/login'
    | '/it-service/onboarding'
    | '/it-service/privacy'
    | '/it-service/profile'
    | '/it-service/reports'
    | '/it-service/security'
    | '/it-service/settings'
    | '/it-service/taxation'
    | '/it-service/vendor'
    | '/partner/assignments'
    | '/partner/chat'
    | '/partner/deliverables'
    | '/partner/earnings'
    | '/partner/feed'
    | '/partner/templates'
    | '/admin'
    | '/founder'
    | '/partner'
    | '/founder/ai/compliance'
    | '/founder/ai/finance'
    | '/founder/ai/growth'
    | '/founder/books/banking'
    | '/founder/books/connectors'
    | '/founder/books/expenses'
    | '/founder/books/invoices'
    | '/founder/books/reports'
    | '/founder/orders/$orderId'
    | '/founder/books'
    | '/founder/marketplace'
    | '/founder/orders'
    | '/api/public/zoho/callback'
    | '/founder/marketplace/order/$serviceId'
  id:
    | '__root__'
    | '/'
    | '/fintech'
    | '/govt'
    | '/healthcare'
    | '/it'
    | '/it-service'
    | '/login'
    | '/msme'
    | '/admin/bi'
    | '/admin/catalogue'
    | '/admin/customers'
    | '/admin/intake'
    | '/admin/orders'
    | '/admin/partners'
    | '/admin/sla'
    | '/founder/billing'
    | '/founder/calendar'
    | '/founder/data-center'
    | '/founder/kpis'
    | '/founder/payroll'
    | '/founder/profile'
    | '/founder/regulatory'
    | '/founder/vault'
    | '/it-service/calendar'
    | '/it-service/dashboard'
    | '/it-service/evidence'
    | '/it-service/financial'
    | '/it-service/governance'
    | '/it-service/hr'
    | '/it-service/insights'
    | '/it-service/legal'
    | '/it-service/login'
    | '/it-service/onboarding'
    | '/it-service/privacy'
    | '/it-service/profile'
    | '/it-service/reports'
    | '/it-service/security'
    | '/it-service/settings'
    | '/it-service/taxation'
    | '/it-service/vendor'
    | '/partner/assignments'
    | '/partner/chat'
    | '/partner/deliverables'
    | '/partner/earnings'
    | '/partner/feed'
    | '/partner/templates'
    | '/admin/'
    | '/founder/'
    | '/partner/'
    | '/founder/ai/compliance'
    | '/founder/ai/finance'
    | '/founder/ai/growth'
    | '/founder/books/banking'
    | '/founder/books/connectors'
    | '/founder/books/expenses'
    | '/founder/books/invoices'
    | '/founder/books/reports'
    | '/founder/orders_/$orderId'
    | '/founder/books/'
    | '/founder/marketplace/'
    | '/founder/orders/'
    | '/api/public/zoho/callback'
    | '/founder/marketplace_/order/$serviceId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FintechRoute: typeof FintechRoute
  GovtRoute: typeof GovtRoute
  HealthcareRoute: typeof HealthcareRoute
  ItRoute: typeof ItRoute
  ItServiceRoute: typeof ItServiceRouteWithChildren
  LoginRoute: typeof LoginRoute
  MsmeRoute: typeof MsmeRoute
  AdminBiRoute: typeof AdminBiRoute
  AdminCatalogueRoute: typeof AdminCatalogueRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminIntakeRoute: typeof AdminIntakeRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminPartnersRoute: typeof AdminPartnersRoute
  AdminSlaRoute: typeof AdminSlaRoute
  FounderBillingRoute: typeof FounderBillingRoute
  FounderCalendarRoute: typeof FounderCalendarRoute
  FounderDataCenterRoute: typeof FounderDataCenterRoute
  FounderKpisRoute: typeof FounderKpisRoute
  FounderPayrollRoute: typeof FounderPayrollRoute
  FounderProfileRoute: typeof FounderProfileRoute
  FounderRegulatoryRoute: typeof FounderRegulatoryRoute
  FounderVaultRoute: typeof FounderVaultRoute
  PartnerAssignmentsRoute: typeof PartnerAssignmentsRoute
  PartnerChatRoute: typeof PartnerChatRoute
  PartnerDeliverablesRoute: typeof PartnerDeliverablesRoute
  PartnerEarningsRoute: typeof PartnerEarningsRoute
  PartnerFeedRoute: typeof PartnerFeedRoute
  PartnerTemplatesRoute: typeof PartnerTemplatesRoute
  AdminIndexRoute: typeof AdminIndexRoute
  FounderIndexRoute: typeof FounderIndexRoute
  PartnerIndexRoute: typeof PartnerIndexRoute
  FounderAiComplianceRoute: typeof FounderAiComplianceRoute
  FounderAiFinanceRoute: typeof FounderAiFinanceRoute
  FounderAiGrowthRoute: typeof FounderAiGrowthRoute
  FounderBooksBankingRoute: typeof FounderBooksBankingRoute
  FounderBooksConnectorsRoute: typeof FounderBooksConnectorsRoute
  FounderBooksExpensesRoute: typeof FounderBooksExpensesRoute
  FounderBooksInvoicesRoute: typeof FounderBooksInvoicesRoute
  FounderBooksReportsRoute: typeof FounderBooksReportsRoute
  FounderOrdersOrderIdRoute: typeof FounderOrdersOrderIdRoute
  FounderBooksIndexRoute: typeof FounderBooksIndexRoute
  FounderMarketplaceIndexRoute: typeof FounderMarketplaceIndexRoute
  FounderOrdersIndexRoute: typeof FounderOrdersIndexRoute
  ApiPublicZohoCallbackRoute: typeof ApiPublicZohoCallbackRoute
  FounderMarketplaceOrderServiceIdRoute: typeof FounderMarketplaceOrderServiceIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/msme': {
      id: '/msme'
      path: '/msme'
      fullPath: '/msme'
      preLoaderRoute: typeof MsmeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/it-service': {
      id: '/it-service'
      path: '/it-service'
      fullPath: '/it-service'
      preLoaderRoute: typeof ItServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/it': {
      id: '/it'
      path: '/it'
      fullPath: '/it'
      preLoaderRoute: typeof ItRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/healthcare': {
      id: '/healthcare'
      path: '/healthcare'
      fullPath: '/healthcare'
      preLoaderRoute: typeof HealthcareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/govt': {
      id: '/govt'
      path: '/govt'
      fullPath: '/govt'
      preLoaderRoute: typeof GovtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fintech': {
      id: '/fintech'
      path: '/fintech'
      fullPath: '/fintech'
      preLoaderRoute: typeof FintechRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/': {
      id: '/partner/'
      path: '/partner'
      fullPath: '/partner/'
      preLoaderRoute: typeof PartnerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/founder/': {
      id: '/founder/'
      path: '/founder'
      fullPath: '/founder/'
      preLoaderRoute: typeof FounderIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/templates': {
      id: '/partner/templates'
      path: '/partner/templates'
      fullPath: '/partner/templates'
      preLoaderRoute: typeof PartnerTemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/feed': {
      id: '/partner/feed'
      path: '/partner/feed'
      fullPath: '/partner/feed'
      preLoaderRoute: typeof PartnerFeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/earnings': {
      id: '/partner/earnings'
      path: '/partner/earnings'
      fullPath: '/partner/earnings'
      preLoaderRoute: typeof PartnerEarningsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/deliverables': {
      id: '/partner/deliverables'
      path: '/partner/deliverables'
      fullPath: '/partner/deliverables'
      preLoaderRoute: typeof PartnerDeliverablesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/chat': {
      id: '/partner/chat'
      path: '/partner/chat'
      fullPath: '/partner/chat'
      preLoaderRoute: typeof PartnerChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/assignments': {
      id: '/partner/assignments'
      path: '/partner/assignments'
      fullPath: '/partner/assignments'
      preLoaderRoute: typeof PartnerAssignmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/it-service/vendor': {
      id: '/it-service/vendor'
      path: '/vendor'
      fullPath: '/it-service/vendor'
      preLoaderRoute: typeof ItServiceVendorRouteImport
      parentRoute: typeof ItServiceRoute
    }
    '/it-service/taxation': {
      id: '/it-service/taxation'
      path: '/taxation'
      fullPath: '/it-service/taxation'
      preLoaderRoute: typeof ItServiceTaxationRouteImport
      parentRoute: typeof ItServiceRoute
    }
    '/it-service/settings': {
      id: '/it-service/settings'
      path: '/settings'
      fullPath: '/it-service/settings'
      preLoaderRoute: typeof ItServiceSettingsRouteImport
      parentRoute: typeof ItServiceRoute
    }
    '/it-service/security': {
      id: '/it-service/security'
      path: '/security'
      fullPath: '/it-service/security'
      preLoaderRoute: typeof ItServiceSecurityRouteImport
      parentRoute: typeof ItServiceRoute
    }
    '/it-service/reports': {
      id: '/it-service/reports'
      path: '/reports'
      fullPath: '/it-service/reports'
      preLoaderRoute: typeof ItServiceReportsRouteImport
      parentRoute: typeof ItServiceRoute
    }
    '/it-service/profile': {
      id: '/it-service/profile'
      path: '/profile'
      fullPath: '/it-service/profile'
      preLoaderRoute: typeof ItServiceProfileRouteImport
      parentRoute: typeof ItServiceRoute
    }
    '/it-service/privacy': {
      id: '/it-service/privacy'
      path: '/privacy'
      fullPath: '/it-service/privacy'
      preLoaderRoute: typeof ItServicePrivacyRouteImport
      parentRoute: typeof ItServiceRoute
    }
    '/it-service/onboarding': {
      id: '/it-service/onboarding'
      path: '/onboarding'
      fullPath: '/it-service/onboarding'
      preLoaderRoute: typeof ItServiceOnboardingRouteImport
      parentRoute: typeof ItServiceRoute
    }
    '/it-service/login': {
      id: '/it-service/login'
      path: '/login'
      fullPath: '/it-service/login'
      preLoaderRoute: typeof ItServiceLoginRouteImport
      parentRoute: typeof ItServiceRoute
    }
    '/it-service/legal': {
      id: '/it-service/legal'
      path: '/legal'
      fullPath: '/it-service/legal'
      preLoaderRoute: typeof ItServiceLegalRouteImport
      parentRoute: typeof ItServiceRoute
    }
    '/it-service/insights': {
      id: '/it-service/insights'
      path: '/insights'
      fullPath: '/it-service/insights'
      preLoaderRoute: typeof ItServiceInsightsRouteImport
      parentRoute: typeof ItServiceRoute
    }
    '/it-service/hr': {
      id: '/it-service/hr'
      path: '/hr'
      fullPath: '/it-service/hr'
      preLoaderRoute: typeof ItServiceHrRouteImport
      parentRoute: typeof ItServiceRoute
    }
    '/it-service/governance': {
      id: '/it-service/governance'
      path: '/governance'
      fullPath: '/it-service/governance'
      preLoaderRoute: typeof ItServiceGovernanceRouteImport
      parentRoute: typeof ItServiceRoute
    }
    '/it-service/financial': {
      id: '/it-service/financial'
      path: '/financial'
      fullPath: '/it-service/financial'
      preLoaderRoute: typeof ItServiceFinancialRouteImport
      parentRoute: typeof ItServiceRoute
    }
    '/it-service/evidence': {
      id: '/it-service/evidence'
      path: '/evidence'
      fullPath: '/it-service/evidence'
      preLoaderRoute: typeof ItServiceEvidenceRouteImport
      parentRoute: typeof ItServiceRoute
    }
    '/it-service/dashboard': {
      id: '/it-service/dashboard'
      path: '/dashboard'
      fullPath: '/it-service/dashboard'
      preLoaderRoute: typeof ItServiceDashboardRouteImport
      parentRoute: typeof ItServiceRoute
    }
    '/it-service/calendar': {
      id: '/it-service/calendar'
      path: '/calendar'
      fullPath: '/it-service/calendar'
      preLoaderRoute: typeof ItServiceCalendarRouteImport
      parentRoute: typeof ItServiceRoute
    }
    '/founder/vault': {
      id: '/founder/vault'
      path: '/founder/vault'
      fullPath: '/founder/vault'
      preLoaderRoute: typeof FounderVaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/founder/regulatory': {
      id: '/founder/regulatory'
      path: '/founder/regulatory'
      fullPath: '/founder/regulatory'
      preLoaderRoute: typeof FounderRegulatoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/founder/profile': {
      id: '/founder/profile'
      path: '/founder/profile'
      fullPath: '/founder/profile'
      preLoaderRoute: typeof FounderProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/founder/payroll': {
      id: '/founder/payroll'
      path: '/founder/payroll'
      fullPath: '/founder/payroll'
      preLoaderRoute: typeof FounderPayrollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/founder/kpis': {
      id: '/founder/kpis'
      path: '/founder/kpis'
      fullPath: '/founder/kpis'
      preLoaderRoute: typeof FounderKpisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/founder/data-center': {
      id: '/founder/data-center'
      path: '/founder/data-center'
      fullPath: '/founder/data-center'
      preLoaderRoute: typeof FounderDataCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/founder/calendar': {
      id: '/founder/calendar'
      path: '/founder/calendar'
      fullPath: '/founder/calendar'
      preLoaderRoute: typeof FounderCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/founder/billing': {
      id: '/founder/billing'
      path: '/founder/billing'
      fullPath: '/founder/billing'
      preLoaderRoute: typeof FounderBillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/sla': {
      id: '/admin/sla'
      path: '/admin/sla'
      fullPath: '/admin/sla'
      preLoaderRoute: typeof AdminSlaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/partners': {
      id: '/admin/partners'
      path: '/admin/partners'
      fullPath: '/admin/partners'
      preLoaderRoute: typeof AdminPartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/admin/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/intake': {
      id: '/admin/intake'
      path: '/admin/intake'
      fullPath: '/admin/intake'
      preLoaderRoute: typeof AdminIntakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/admin/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/catalogue': {
      id: '/admin/catalogue'
      path: '/admin/catalogue'
      fullPath: '/admin/catalogue'
      preLoaderRoute: typeof AdminCatalogueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/bi': {
      id: '/admin/bi'
      path: '/admin/bi'
      fullPath: '/admin/bi'
      preLoaderRoute: typeof AdminBiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/founder/orders/': {
      id: '/founder/orders/'
      path: '/founder/orders'
      fullPath: '/founder/orders/'
      preLoaderRoute: typeof FounderOrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/founder/marketplace/': {
      id: '/founder/marketplace/'
      path: '/founder/marketplace'
      fullPath: '/founder/marketplace/'
      preLoaderRoute: typeof FounderMarketplaceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/founder/books/': {
      id: '/founder/books/'
      path: '/founder/books'
      fullPath: '/founder/books/'
      preLoaderRoute: typeof FounderBooksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/founder/orders_/$orderId': {
      id: '/founder/orders_/$orderId'
      path: '/founder/orders/$orderId'
      fullPath: '/founder/orders/$orderId'
      preLoaderRoute: typeof FounderOrdersOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/founder/books/reports': {
      id: '/founder/books/reports'
      path: '/founder/books/reports'
      fullPath: '/founder/books/reports'
      preLoaderRoute: typeof FounderBooksReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/founder/books/invoices': {
      id: '/founder/books/invoices'
      path: '/founder/books/invoices'
      fullPath: '/founder/books/invoices'
      preLoaderRoute: typeof FounderBooksInvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/founder/books/expenses': {
      id: '/founder/books/expenses'
      path: '/founder/books/expenses'
      fullPath: '/founder/books/expenses'
      preLoaderRoute: typeof FounderBooksExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/founder/books/connectors': {
      id: '/founder/books/connectors'
      path: '/founder/books/connectors'
      fullPath: '/founder/books/connectors'
      preLoaderRoute: typeof FounderBooksConnectorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/founder/books/banking': {
      id: '/founder/books/banking'
      path: '/founder/books/banking'
      fullPath: '/founder/books/banking'
      preLoaderRoute: typeof FounderBooksBankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/founder/ai/growth': {
      id: '/founder/ai/growth'
      path: '/founder/ai/growth'
      fullPath: '/founder/ai/growth'
      preLoaderRoute: typeof FounderAiGrowthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/founder/ai/finance': {
      id: '/founder/ai/finance'
      path: '/founder/ai/finance'
      fullPath: '/founder/ai/finance'
      preLoaderRoute: typeof FounderAiFinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/founder/ai/compliance': {
      id: '/founder/ai/compliance'
      path: '/founder/ai/compliance'
      fullPath: '/founder/ai/compliance'
      preLoaderRoute: typeof FounderAiComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/founder/marketplace_/order/$serviceId': {
      id: '/founder/marketplace_/order/$serviceId'
      path: '/founder/marketplace/order/$serviceId'
      fullPath: '/founder/marketplace/order/$serviceId'
      preLoaderRoute: typeof FounderMarketplaceOrderServiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/zoho/callback': {
      id: '/api/public/zoho/callback'
      path: '/api/public/zoho/callback'
      fullPath: '/api/public/zoho/callback'
      preLoaderRoute: typeof ApiPublicZohoCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ItServiceRouteChildren {
  ItServiceCalendarRoute: typeof ItServiceCalendarRoute
  ItServiceDashboardRoute: typeof ItServiceDashboardRoute
  ItServiceEvidenceRoute: typeof ItServiceEvidenceRoute
  ItServiceFinancialRoute: typeof ItServiceFinancialRoute
  ItServiceGovernanceRoute: typeof ItServiceGovernanceRoute
  ItServiceHrRoute: typeof ItServiceHrRoute
  ItServiceInsightsRoute: typeof ItServiceInsightsRoute
  ItServiceLegalRoute: typeof ItServiceLegalRoute
  ItServiceLoginRoute: typeof ItServiceLoginRoute
  ItServiceOnboardingRoute: typeof ItServiceOnboardingRoute
  ItServicePrivacyRoute: typeof ItServicePrivacyRoute
  ItServiceProfileRoute: typeof ItServiceProfileRoute
  ItServiceReportsRoute: typeof ItServiceReportsRoute
  ItServiceSecurityRoute: typeof ItServiceSecurityRoute
  ItServiceSettingsRoute: typeof ItServiceSettingsRoute
  ItServiceTaxationRoute: typeof ItServiceTaxationRoute
  ItServiceVendorRoute: typeof ItServiceVendorRoute
}

const ItServiceRouteChildren: ItServiceRouteChildren = {
  ItServiceCalendarRoute: ItServiceCalendarRoute,
  ItServiceDashboardRoute: ItServiceDashboardRoute,
  ItServiceEvidenceRoute: ItServiceEvidenceRoute,
  ItServiceFinancialRoute: ItServiceFinancialRoute,
  ItServiceGovernanceRoute: ItServiceGovernanceRoute,
  ItServiceHrRoute: ItServiceHrRoute,
  ItServiceInsightsRoute: ItServiceInsightsRoute,
  ItServiceLegalRoute: ItServiceLegalRoute,
  ItServiceLoginRoute: ItServiceLoginRoute,
  ItServiceOnboardingRoute: ItServiceOnboardingRoute,
  ItServicePrivacyRoute: ItServicePrivacyRoute,
  ItServiceProfileRoute: ItServiceProfileRoute,
  ItServiceReportsRoute: ItServiceReportsRoute,
  ItServiceSecurityRoute: ItServiceSecurityRoute,
  ItServiceSettingsRoute: ItServiceSettingsRoute,
  ItServiceTaxationRoute: ItServiceTaxationRoute,
  ItServiceVendorRoute: ItServiceVendorRoute,
}

const ItServiceRouteWithChildren = ItServiceRoute._addFileChildren(
  ItServiceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FintechRoute: FintechRoute,
  GovtRoute: GovtRoute,
  HealthcareRoute: HealthcareRoute,
  ItRoute: ItRoute,
  ItServiceRoute: ItServiceRouteWithChildren,
  LoginRoute: LoginRoute,
  MsmeRoute: MsmeRoute,
  AdminBiRoute: AdminBiRoute,
  AdminCatalogueRoute: AdminCatalogueRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminIntakeRoute: AdminIntakeRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminPartnersRoute: AdminPartnersRoute,
  AdminSlaRoute: AdminSlaRoute,
  FounderBillingRoute: FounderBillingRoute,
  FounderCalendarRoute: FounderCalendarRoute,
  FounderDataCenterRoute: FounderDataCenterRoute,
  FounderKpisRoute: FounderKpisRoute,
  FounderPayrollRoute: FounderPayrollRoute,
  FounderProfileRoute: FounderProfileRoute,
  FounderRegulatoryRoute: FounderRegulatoryRoute,
  FounderVaultRoute: FounderVaultRoute,
  PartnerAssignmentsRoute: PartnerAssignmentsRoute,
  PartnerChatRoute: PartnerChatRoute,
  PartnerDeliverablesRoute: PartnerDeliverablesRoute,
  PartnerEarningsRoute: PartnerEarningsRoute,
  PartnerFeedRoute: PartnerFeedRoute,
  PartnerTemplatesRoute: PartnerTemplatesRoute,
  AdminIndexRoute: AdminIndexRoute,
  FounderIndexRoute: FounderIndexRoute,
  PartnerIndexRoute: PartnerIndexRoute,
  FounderAiComplianceRoute: FounderAiComplianceRoute,
  FounderAiFinanceRoute: FounderAiFinanceRoute,
  FounderAiGrowthRoute: FounderAiGrowthRoute,
  FounderBooksBankingRoute: FounderBooksBankingRoute,
  FounderBooksConnectorsRoute: FounderBooksConnectorsRoute,
  FounderBooksExpensesRoute: FounderBooksExpensesRoute,
  FounderBooksInvoicesRoute: FounderBooksInvoicesRoute,
  FounderBooksReportsRoute: FounderBooksReportsRoute,
  FounderOrdersOrderIdRoute: FounderOrdersOrderIdRoute,
  FounderBooksIndexRoute: FounderBooksIndexRoute,
  FounderMarketplaceIndexRoute: FounderMarketplaceIndexRoute,
  FounderOrdersIndexRoute: FounderOrdersIndexRoute,
  ApiPublicZohoCallbackRoute: ApiPublicZohoCallbackRoute,
  FounderMarketplaceOrderServiceIdRoute: FounderMarketplaceOrderServiceIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
